FROM node:18-slim as base

WORKDIR /app
ENV PNPM_HOME=/usr/local/bin

RUN npm i -g pnpm
RUN pnpm add -g turbo

# ? -------------------------

FROM base AS builder

COPY . .
RUN turbo prune --scope=@hackth/cms --docker

# ? -------------------------

FROM base AS installer

WORKDIR /app

COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm i

COPY --from=builder /app/out/full/ .
RUN turbo run build --filter=@hackth/cms

RUN rm -rf **/node_modules && pnpm i --prod

# ? -------------------------

FROM gcr.io/distroless/nodejs18-debian11:nonroot as runner

WORKDIR /app

USER nonroot
ENV NODE_ENV production
ENV PAYLOAD_CONFIG_PATH apps/cms/dist/payload.config.js

EXPOSE 3000


COPY --from=installer /app/node_modules ./node_modules
COPY --from=installer /app/apps/cms/dist ./apps/cms/dist
COPY --from=installer /app/apps/cms/build ./apps/cms/build
COPY --from=installer /app/apps/cms/node_modules ./apps/cms/node_modules

CMD ["./apps/cms/dist/server.js"]
