/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    apis: Api;
    hackathons: Hackathon;
    organizations: Organization;
    pains: Pain;
    projects: Project;
    services: Service;
    users: User;
  };
  globals: {};
}
export interface Api {
  id: string;
  name: string;
  projects?: string[] | Project[];
  updatedAt: string;
  createdAt: string;
}
export interface Project {
  id: string;
  name: string;
  slug?: string;
  description?: {
    [k: string]: unknown;
  }[];
  status: 'NOT_STARTED' | 'IN_DEVELOPMENT' | 'RELEASED' | 'DONE';
  organizations?: string[] | Organization[];
  apis?: string[] | Api[];
  pains?: string[] | Pain[];
  hackathons?: string[] | Hackathon[];
  updatedAt: string;
  createdAt: string;
}
export interface Organization {
  id: string;
  name: string;
  tags?: 'Civic' | 'Government';
  projects?: string[] | Project[];
  updatedAt: string;
  createdAt: string;
}
export interface Pain {
  id: string;
  problem: string;
  organizations?: string[] | Organization[];
  projects?: string[] | Project[];
  updatedAt: string;
  createdAt: string;
}
export interface Hackathon {
  id: string;
  name: string;
  organizations?: string[] | Organization[];
  projects?: string[] | Project[];
  updatedAt: string;
  createdAt: string;
}
export interface Service {
  id: string;
  name: string;
  project?: string[] | Project[];
  apis?: string[] | Api[];
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
