name: Deployments

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  packages: write

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: ${{ matrix.context }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: [web, cms]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: buildx
        uses: docker/setup-buildx-action@v2
      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-${{ matrix.context }}
      - name: publish
        uses: deploys-app/deploys-action@v1
        with:
          project: ${{ secrets.DEPLOYS_NAME }}
          location: gke.cluster-rcf2
          name: hackth-${{ matrix.context }}
          image: ghcr.io/${{ github.repository }}-${{ matrix.context }}
          minReplicas: 1
          maxReplicas: 2
        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
